package api;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Moderators")
public class ModeratorRegistration 
{
    protected String id;
    
    protected String username;
    
    protected String password;

    @DynamoDBHashKey(attributeName="Id")
    @DynamoDBAutoGeneratedKey
    public String getId() 
    {
        return this.id;
    }

    public void setId(String id) 
    {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName="Username")
    public String getUsername() 
    {
        return this.username;
    }

    public void setUsername(String username) 
    {
        this.username = username;
    }

    @DynamoDBAttribute(attributeName="Password")
    public String getPassword() 
    {
        return this.password;
    }

    public void setPassword(String password) 
    {
        this.password = password;
    }

    public ModeratorRegistration()
    {
    	
    }

    public ModeratorRegistration(String username, String password) 
    {
        this.username = username;
        
        this.password = password;
    }
}