#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Announcement.Android.Resource", IsApplication=true)]

namespace Announcement.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::Announcement.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Announcement.Android.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::Announcement.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Announcement.Android.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in_animation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out_animation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int grow_fade_in_center = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int progress_animation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_backward_in_animation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_backward_out_animation = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_forward_in_animation = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_forward_out_animation = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int backgroundColor = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int borderColor = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int borderWidth = 2130771988;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_auxiliary_view_position = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_confirm_logout = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_foreground_color = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_horizontal_alignment = 2130771976;
			
			// aapt resource value: 0x7f01000e
			public const int com_facebook_is_cropped = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_login_text = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_logout_text = 2130771979;
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_object_id = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_object_type = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int com_facebook_preset_size = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_style = 2130771974;
			
			// aapt resource value: 0x7f01000c
			public const int com_facebook_tooltip_mode = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontName = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010013
			public const int lineColor = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int lineWidthPercent = 2130771989;
			
			// aapt resource value: 0x7f01000f
			public const int localizationKey = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060022
			public const int button_normal = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int button_pressed = 2131099681;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_blue = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_button_background_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_button_background_color_disabled = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_button_background_color_pressed = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_button_like_background_color_selected = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_button_login_silver_background_color = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_button_send_background_color = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_button_send_background_color_pressed = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_likeboxcountview_border_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_likeboxcountview_text_color = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_likeview_text_color = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_share_button_text_color = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f06002c
			public const int common_signin_btn_text_dark = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int common_signin_btn_text_light = 2131099693;
			
			// aapt resource value: 0x7f060018
			public const int facebook_button_normal = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int facebook_button_pressed = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int google_plus_button_normal = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int google_plus_button_pressed = 2131099673;
			
			// aapt resource value: 0x7f060025
			public const int grey_color = 2131099685;
			
			// aapt resource value: 0x7f06002b
			public const int hint_major_color = 2131099691;
			
			// aapt resource value: 0x7f06001c
			public const int linked_in_button_normal = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int linked_in_button_pressed = 2131099675;
			
			// aapt resource value: 0x7f060028
			public const int list_item_pressed_color = 2131099688;
			
			// aapt resource value: 0x7f060023
			public const int major_color = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int major_divider_color = 2131099684;
			
			// aapt resource value: 0x7f060020
			public const int moderator_button_normal = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int moderator_button_pressed = 2131099679;
			
			// aapt resource value: 0x7f060027
			public const int progress_background = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int progress_transparent = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int text_selector_normal_color = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int text_selector_not_focused_color = 2131099690;
			
			// aapt resource value: 0x7f06001e
			public const int vk_button_normal = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int vk_button_pressed = 2131099677;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_likeboxcountview_border_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_likeboxcountview_border_width = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int com_facebook_likeboxcountview_caret_height = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int com_facebook_likeboxcountview_caret_width = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int com_facebook_likeboxcountview_text_padding = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int com_facebook_likeboxcountview_text_size = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int com_facebook_likeview_edge_padding = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int com_facebook_likeview_internal_padding = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int com_facebook_likeview_text_size = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int com_facebook_profilepictureview_preset_size_large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int com_facebook_share_button_padding_bottom = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_share_button_padding_left = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_share_button_padding_right = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_share_button_padding_top = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_share_button_text_size = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_tooltip_horizontal_padding = 2131230738;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int big_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int camera_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_like_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_like_icon_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_login_silver_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_send_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_send_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_close = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_profile_picture_blank_portrait = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_profile_picture_blank_square = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_black_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_black_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_black_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_black_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_blue_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_blue_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_blue_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_blue_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_full_open_on_phone = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_disabled_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_disabled_focus_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_disabled_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_focus_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_icon_focus_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_icon_normal_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_icon_normal_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_icon_pressed_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_icon_pressed_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_disabled_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_disabled_focus_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_disabled_focus_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_disabled_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_focus_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_text_focus_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_signin_btn_text_normal_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_signin_btn_text_normal_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_signin_btn_text_pressed_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_signin_btn_text_pressed_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int delete_icon = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int facebook_button_selector = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int fb_login_icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int google_login_icon = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int google_plus_button_selector = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_plusone_medium_off_client = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_plusone_small_off_client = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_plusone_standard_off_client = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_plusone_tall_off_client = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Icon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int in_login_icon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int linked_in_button_selector = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int list_item_selector = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int login_background = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int login_fields_background = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int logo = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int menu_button_pressed = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int menu_button_released = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int menu_button_selector = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int messenger_bubble_large_blue = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int messenger_bubble_large_white = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int messenger_bubble_small_blue = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int messenger_bubble_small_white = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int messenger_button_blue_bg_round = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int messenger_button_blue_bg_selector = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int messenger_button_send_round_shadow = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int messenger_button_white_bg_round = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int messenger_button_white_bg_selector = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int moderator_button_selector = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int progress_background = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int progress_border = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int progress_loading = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int progress_loading_old = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int rating_radio_button_selector = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int rating_radio_button_text_color = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int report_spam_button_selector = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int splash = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int splash_screen = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int tab_indicator_pressed = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int tab_indicator_selected = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int tab_indicator_selector = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int tab_indicator_text_color_selector = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int tab_indicator_unselected = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int vk_button_selector = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int vk_login_icon = 2130837596;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0039
			public const int Complaints = 2131361849;
			
			// aapt resource value: 0x7f0a0045
			public const int Confirmed = 2131361861;
			
			// aapt resource value: 0x7f0a0044
			public const int ConfirmedReportsLine = 2131361860;
			
			// aapt resource value: 0x7f0a002c
			public const int Delete = 2131361836;
			
			// aapt resource value: 0x7f0a0023
			public const int FacebookButton = 2131361827;
			
			// aapt resource value: 0x7f0a0028
			public const int FragmentContainer = 2131361832;
			
			// aapt resource value: 0x7f0a0024
			public const int GooglePlusButton = 2131361828;
			
			// aapt resource value: 0x7f0a0027
			public const int HeaderContainer = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int LinkedInButton = 2131361830;
			
			// aapt resource value: 0x7f0a0022
			public const int LoginButton = 2131361826;
			
			// aapt resource value: 0x7f0a0015
			public const int LoginEditText = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int PasswordEditText = 2131361814;
			
			// aapt resource value: 0x7f0a003b
			public const int RatingsViewSwitcher = 2131361851;
			
			// aapt resource value: 0x7f0a0046
			public const int Reports = 2131361862;
			
			// aapt resource value: 0x7f0a002a
			public const int ScrollView = 2131361834;
			
			// aapt resource value: 0x7f0a003c
			public const int SpammersSwipeRefresh = 2131361852;
			
			// aapt resource value: 0x7f0a002b
			public const int Title = 2131361835;
			
			// aapt resource value: 0x7f0a003e
			public const int UsersSwipeRefresh = 2131361854;
			
			// aapt resource value: 0x7f0a0025
			public const int VKButton = 2131361829;
			
			// aapt resource value: 0x7f0a0000
			public const int adjust_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int adjust_width = 2131361793;
			
			// aapt resource value: 0x7f0a0038
			public const int alertBtnDismiss = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int alertBtnRetry = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int alertText1 = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int alertTitle = 2131361845;
			
			// aapt resource value: 0x7f0a000f
			public const int automatic = 2131361807;
			
			// aapt resource value: 0x7f0a0009
			public const int bottom = 2131361801;
			
			// aapt resource value: 0x7f0a0006
			public const int box_count = 2131361798;
			
			// aapt resource value: 0x7f0a0017
			public const int btnAdd = 2131361815;
			
			// aapt resource value: 0x7f0a0033
			public const int btnConfirm = 2131361843;
			
			// aapt resource value: 0x7f0a0020
			public const int btnMenu = 2131361824;
			
			// aapt resource value: 0x7f0a0034
			public const int btnReject = 2131361844;
			
			// aapt resource value: 0x7f0a0043
			public const int btnReportSpam = 2131361859;
			
			// aapt resource value: 0x7f0a0041
			public const int btnSpammers = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int btnUsers = 2131361858;
			
			// aapt resource value: 0x7f0a0007
			public const int button = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int center = 2131361804;
			
			// aapt resource value: 0x7f0a001b
			public const int com_facebook_body_frame = 2131361819;
			
			// aapt resource value: 0x7f0a001d
			public const int com_facebook_button_xout = 2131361821;
			
			// aapt resource value: 0x7f0a0019
			public const int com_facebook_fragment_container = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int com_facebook_login_activity_progress_bar = 2131361818;
			
			// aapt resource value: 0x7f0a001f
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361823;
			
			// aapt resource value: 0x7f0a001e
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361822;
			
			// aapt resource value: 0x7f0a001c
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361820;
			
			// aapt resource value: 0x7f0a0010
			public const int display_always = 2131361808;
			
			// aapt resource value: 0x7f0a003a
			public const int indicatorTextView = 2131361850;
			
			// aapt resource value: 0x7f0a000a
			public const int inline = 2131361802;
			
			// aapt resource value: 0x7f0a0012
			public const int large = 2131361810;
			
			// aapt resource value: 0x7f0a000d
			public const int left = 2131361805;
			
			// aapt resource value: 0x7f0a002d
			public const int listView = 2131361837;
			
			// aapt resource value: 0x7f0a0021
			public const int logo = 2131361825;
			
			// aapt resource value: 0x7f0a0029
			public const int messenger_send_button = 2131361833;
			
			// aapt resource value: 0x7f0a0011
			public const int never_display = 2131361809;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0013
			public const int normal = 2131361811;
			
			// aapt resource value: 0x7f0a0003
			public const int open_graph = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int page = 2131361796;
			
			// aapt resource value: 0x7f0a0047
			public const int pagerImageView = 2131361863;
			
			// aapt resource value: 0x7f0a002f
			public const int progressTitle = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int progressView = 2131361840;
			
			// aapt resource value: 0x7f0a0040
			public const int ratingRadioGroup = 2131361856;
			
			// aapt resource value: 0x7f0a0032
			public const int reportPhoneNumber = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int reportViewPager = 2131361841;
			
			// aapt resource value: 0x7f0a000e
			public const int right = 2131361806;
			
			// aapt resource value: 0x7f0a0014
			public const int small = 2131361812;
			
			// aapt resource value: 0x7f0a003d
			public const int spammersListView = 2131361853;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a0018
			public const int tabHost = 2131361816;
			
			// aapt resource value: 0x7f0a002e
			public const int textView = 2131361838;
			
			// aapt resource value: 0x7f0a000b
			public const int top = 2131361803;
			
			// aapt resource value: 0x7f0a0005
			public const int unknown = 2131361797;
			
			// aapt resource value: 0x7f0a003f
			public const int usersListView = 2131361855;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_new_moderator_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int admin_main_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_activity_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_login_fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_tooltip_bubble = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int header_view = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int messenger_button_send_blue_large = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int messenger_button_send_blue_round = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int messenger_button_send_blue_small = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int messenger_button_send_white_large = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int messenger_button_send_white_round = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int messenger_button_send_white_small = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int moderator_list_item_template = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int popup_menu = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int popup_menu_item = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int progress_borderless_layout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int progress_layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int report_validation_view = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int simple_alert = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int spammers_list_item_template = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int tab_indicator = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int tab_rating = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int user_main_layout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int users_list_item_template = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int validation_images_pager_view = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int validation_list_item_template = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050034
			public const int ApplicationName = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int Hello = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int app_name = 2131034166;
			
			// aapt resource value: 0x7f050001
			public const int auth_google_play_services_client_facebook_display_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int auth_google_play_services_client_google_display_name = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int com_facebook_image_download_unknown_error = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int com_facebook_internet_permission_error_message = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int com_facebook_internet_permission_error_title = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int com_facebook_like_button_liked = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int com_facebook_like_button_not_liked = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int com_facebook_loading = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int com_facebook_loginview_cancel_action = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int com_facebook_loginview_log_in_button = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int com_facebook_loginview_log_in_button_long = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int com_facebook_loginview_log_out_action = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int com_facebook_loginview_log_out_button = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int com_facebook_loginview_logged_in_as = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int com_facebook_loginview_logged_in_using_facebook = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int com_facebook_send_button_text = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int com_facebook_share_button_text = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int com_facebook_tooltip_default = 2131034161;
			
			// aapt resource value: 0x7f050004
			public const int common_android_wear_notification_needs_update_text = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int common_android_wear_update_text = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int common_android_wear_update_title = 2131034127;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_api_unavailable_text = 2131034141;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_enable_button = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_enable_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_enable_title = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_install_button = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_install_text_phone = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_install_text_tablet = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_install_title = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_invalid_account_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_invalid_account_title = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_needs_enabling_title = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_network_error_text = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_network_error_title = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_notification_needs_update_title = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_notification_ticker = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_sign_in_failed_text = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_sign_in_failed_title = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_unknown_issue = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_unsupported_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_unsupported_title = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_button = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_text = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_update_title = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_updating_text = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_updating_title = 2131034130;
			
			// aapt resource value: 0x7f05001c
			public const int common_open_on_phone = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int common_signin_button_text = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int common_signin_button_text_long = 2131034145;
			
			// aapt resource value: 0x7f050037
			public const int fb_app_id = 2131034167;
			
			// aapt resource value: 0x7f050035
			public const int hello = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int messenger_send_button_text = 2131034162;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MessengerButton = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MessengerButton_Blue = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int MessengerButton_Blue_Large = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int MessengerButton_Blue_Small = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int MessengerButton_White = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int MessengerButton_White_Large = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int MessengerButton_White_Small = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int MessengerButtonText = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int MessengerButtonText_Blue = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int MessengerButtonText_Blue_Large = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int MessengerButtonText_Blue_Small = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int MessengerButtonText_White = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int MessengerButtonText_White_Large = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int MessengerButtonText_White_Small = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int com_facebook_button = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int com_facebook_button_like = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int com_facebook_button_send = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int com_facebook_button_share = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int com_facebook_loginview_default_style = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int com_facebook_loginview_silver_style = 2131296275;
			
			// aapt resource value: 0x7f090018
			public const int general_theme = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int login_social_button_style = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int main_theme = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int popup_style = 2131296278;
			
			// aapt resource value: 0x7f09001d
			public const int progress_dialog_borderless_theme = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int progress_dialog_style = 2131296286;
			
			// aapt resource value: 0x7f09001c
			public const int progress_dialog_theme = 2131296284;
			
			// aapt resource value: 0x7f090017
			public const int splash_theme = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int text_view_bold_font_style = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int text_view_normal_font_style = 2131296282;
			
			// aapt resource value: 0x7f090014
			public const int tooltip_bubble_text = 2131296276;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			public static int[] font = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int font_fontName = 0;
			
			public static int[] localization = new int[] {
					2130771983};
			
			// aapt resource value: 0
			public const int localization_localizationKey = 0;
			
			public static int[] padding_fix = new int[] {
					16842965,
					16842966,
					16842967,
					16842968,
					16842969};
			
			// aapt resource value: 0
			public const int padding_fix_android_padding = 0;
			
			// aapt resource value: 4
			public const int padding_fix_android_paddingBottom = 4;
			
			// aapt resource value: 1
			public const int padding_fix_android_paddingLeft = 1;
			
			// aapt resource value: 3
			public const int padding_fix_android_paddingRight = 3;
			
			// aapt resource value: 2
			public const int padding_fix_android_paddingTop = 2;
			
			public static int[] progress_indicator = new int[] {
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 0
			public const int progress_indicator_backgroundColor = 0;
			
			// aapt resource value: 1
			public const int progress_indicator_borderColor = 1;
			
			// aapt resource value: 3
			public const int progress_indicator_borderWidth = 3;
			
			// aapt resource value: 2
			public const int progress_indicator_lineColor = 2;
			
			// aapt resource value: 4
			public const int progress_indicator_lineWidthPercent = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
