#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Announcement.Android.Resource", IsApplication=true)]

namespace Announcement.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Announcement.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Announcement.Android.Resource.String.Hello;
			global::PCLCrypto.Resource.String.ApplicationName = global::Announcement.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Announcement.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_auxiliary_view_position = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_confirm_logout = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_foreground_color = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_horizontal_alignment = 2130771976;
			
			// aapt resource value: 0x7f01000e
			public const int com_facebook_is_cropped = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_login_text = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_logout_text = 2130771979;
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_object_id = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_object_type = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int com_facebook_preset_size = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_style = 2130771974;
			
			// aapt resource value: 0x7f01000c
			public const int com_facebook_tooltip_mode = 2130771980;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public const int localizationKey = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050022
			public const int button_normal = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int button_pressed = 2131034145;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_blue = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_button_background_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_button_background_color_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_button_background_color_pressed = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_button_like_background_color_selected = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_button_login_silver_background_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int com_facebook_button_send_background_color = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int com_facebook_button_send_background_color_pressed = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int com_facebook_likeboxcountview_border_color = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int com_facebook_likeboxcountview_text_color = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int com_facebook_likeview_text_color = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int com_facebook_share_button_text_color = 2131034134;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f050025
			public const int common_signin_btn_text_dark = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int common_signin_btn_text_light = 2131034150;
			
			// aapt resource value: 0x7f050018
			public const int facebook_button_normal = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int facebook_button_pressed = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int google_plus_button_normal = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int google_plus_button_pressed = 2131034137;
			
			// aapt resource value: 0x7f050024
			public const int grey_color = 2131034148;
			
			// aapt resource value: 0x7f05001c
			public const int linked_in_button_normal = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int linked_in_button_pressed = 2131034139;
			
			// aapt resource value: 0x7f050023
			public const int major_color = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int moderator_button_normal = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int moderator_button_pressed = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int vk_button_normal = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int vk_button_pressed = 2131034141;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_likeboxcountview_border_radius = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_likeboxcountview_border_width = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_likeboxcountview_caret_height = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_likeboxcountview_caret_width = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_likeboxcountview_text_padding = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_likeboxcountview_text_size = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_likeview_edge_padding = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_likeview_internal_padding = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_likeview_text_size = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_profilepictureview_preset_size_large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_share_button_padding_bottom = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_share_button_padding_left = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_share_button_padding_right = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_share_button_padding_top = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_share_button_text_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_tooltip_horizontal_padding = 2131165202;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int big_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int camera_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_like_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_like_icon_selected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_login_silver_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_send_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_send_icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_close = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_profile_picture_blank_portrait = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_profile_picture_blank_square = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_black_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_black_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_black_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_black_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_blue_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_blue_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_blue_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_blue_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_full_open_on_phone = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_ic_googleplayservices = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_disabled_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_disabled_focus_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_icon_disabled_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_icon_focus_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_icon_focus_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_icon_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_icon_normal_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_icon_normal_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_icon_pressed_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_icon_pressed_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_disabled_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_disabled_focus_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_disabled_focus_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_signin_btn_text_disabled_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_signin_btn_text_focus_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_signin_btn_text_focus_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_signin_btn_text_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_signin_btn_text_normal_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_signin_btn_text_normal_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_signin_btn_text_pressed_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_signin_btn_text_pressed_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int facebook_button_selector = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int fb_login_icon = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int google_login_icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int google_plus_button_selector = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_plusone_medium_off_client = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_plusone_small_off_client = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_plusone_standard_off_client = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_plusone_tall_off_client = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int in_login_icon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int linked_in_button_selector = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int login_background = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int login_fields_background = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int logo = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int menu_button_pressed = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int menu_button_released = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int menu_button_selector = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int messenger_bubble_large_blue = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int messenger_bubble_large_white = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int messenger_bubble_small_blue = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int messenger_bubble_small_white = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int messenger_button_blue_bg_round = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int messenger_button_blue_bg_selector = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int messenger_button_send_round_shadow = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int messenger_button_white_bg_round = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int messenger_button_white_bg_selector = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int moderator_button_selector = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int progress_background = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int progress_loading = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int progress_loading_old = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int rating_radio_button_selector = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int rating_radio_button_text_color = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int report_spam_button_selector = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int splash = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int splash_screen = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int tab_indicator_pressed = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int tab_indicator_selected = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int tab_indicator_selector = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int tab_indicator_unselected = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int vk_button_selector = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int vk_login_icon = 2130837592;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090029
			public const int FacebookButton = 2131296297;
			
			// aapt resource value: 0x7f09002e
			public const int FragmentContainer = 2131296302;
			
			// aapt resource value: 0x7f09002a
			public const int GooglePlusButton = 2131296298;
			
			// aapt resource value: 0x7f09002d
			public const int HeaderContainer = 2131296301;
			
			// aapt resource value: 0x7f09002c
			public const int LinkedInButton = 2131296300;
			
			// aapt resource value: 0x7f090028
			public const int LoginButton = 2131296296;
			
			// aapt resource value: 0x7f090016
			public const int LoginEditText = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int PasswordEditText = 2131296279;
			
			// aapt resource value: 0x7f09002b
			public const int VKButton = 2131296299;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090032
			public const int alertBtnDismiss = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int alertBtnRetry = 2131296307;
			
			// aapt resource value: 0x7f090031
			public const int alertText1 = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int alertTitle = 2131296304;
			
			// aapt resource value: 0x7f09000f
			public const int automatic = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int bottom = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int box_count = 2131296262;
			
			// aapt resource value: 0x7f090018
			public const int btnAdd = 2131296280;
			
			// aapt resource value: 0x7f09003a
			public const int btnItems = 2131296314;
			
			// aapt resource value: 0x7f090015
			public const int btnMenu = 2131296277;
			
			// aapt resource value: 0x7f09003c
			public const int btnReportSpam = 2131296316;
			
			// aapt resource value: 0x7f09003b
			public const int btnUsers = 2131296315;
			
			// aapt resource value: 0x7f090007
			public const int button = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int center = 2131296268;
			
			// aapt resource value: 0x7f09001c
			public const int com_facebook_body_frame = 2131296284;
			
			// aapt resource value: 0x7f09001e
			public const int com_facebook_button_xout = 2131296286;
			
			// aapt resource value: 0x7f09001a
			public const int com_facebook_fragment_container = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int com_facebook_login_activity_progress_bar = 2131296283;
			
			// aapt resource value: 0x7f090020
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296285;
			
			// aapt resource value: 0x7f090010
			public const int display_always = 2131296272;
			
			// aapt resource value: 0x7f090036
			public const int indicatorTextView = 2131296310;
			
			// aapt resource value: 0x7f09000a
			public const int inline = 2131296266;
			
			// aapt resource value: 0x7f090025
			public const int itemConfirmed = 2131296293;
			
			// aapt resource value: 0x7f090023
			public const int itemConfirmedLabel = 2131296291;
			
			// aapt resource value: 0x7f090026
			public const int itemDescription = 2131296294;
			
			// aapt resource value: 0x7f090024
			public const int itemPosts = 2131296292;
			
			// aapt resource value: 0x7f090022
			public const int itemPostsLabel = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int itemTitle = 2131296289;
			
			// aapt resource value: 0x7f090012
			public const int large = 2131296274;
			
			// aapt resource value: 0x7f09000d
			public const int left = 2131296269;
			
			// aapt resource value: 0x7f090027
			public const int logo = 2131296295;
			
			// aapt resource value: 0x7f09002f
			public const int messenger_send_button = 2131296303;
			
			// aapt resource value: 0x7f090011
			public const int never_display = 2131296273;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090013
			public const int normal = 2131296275;
			
			// aapt resource value: 0x7f090003
			public const int open_graph = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int page = 2131296260;
			
			// aapt resource value: 0x7f090034
			public const int progressTitle = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int progressView = 2131296309;
			
			// aapt resource value: 0x7f090039
			public const int ratingRadioGroup = 2131296313;
			
			// aapt resource value: 0x7f09000e
			public const int right = 2131296270;
			
			// aapt resource value: 0x7f090014
			public const int small = 2131296276;
			
			// aapt resource value: 0x7f090037
			public const int spammersListView = 2131296311;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f090019
			public const int tabHost = 2131296281;
			
			// aapt resource value: 0x7f09000b
			public const int top = 2131296267;
			
			// aapt resource value: 0x7f090005
			public const int unknown = 2131296261;
			
			// aapt resource value: 0x7f090038
			public const int usersListView = 2131296312;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_new_moderator_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int admin_main_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_activity_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_login_fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_tooltip_bubble = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int header_view = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_one_item_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int list_two_item_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int login_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int main_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int messenger_button_send_blue_large = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int messenger_button_send_blue_round = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int messenger_button_send_blue_small = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int messenger_button_send_white_large = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int messenger_button_send_white_round = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int messenger_button_send_white_small = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int moderators_layout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int simple_alert = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int simple_progress = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int tab_indicator = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int tab_rating = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int user_main_layout = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040036
			public const int app_name = 2130968630;
			
			// aapt resource value: 0x7f040003
			public const int auth_google_play_services_client_facebook_display_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int auth_google_play_services_client_google_display_name = 2130968578;
			
			// aapt resource value: 0x7f040024
			public const int com_facebook_image_download_unknown_error = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int com_facebook_internet_permission_error_message = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int com_facebook_internet_permission_error_title = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int com_facebook_like_button_liked = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int com_facebook_like_button_not_liked = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int com_facebook_loading = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int com_facebook_loginview_cancel_action = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int com_facebook_loginview_log_in_button = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int com_facebook_loginview_log_in_button_long = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int com_facebook_loginview_log_out_action = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int com_facebook_loginview_log_out_button = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int com_facebook_loginview_logged_in_as = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int com_facebook_send_button_text = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int com_facebook_share_button_text = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int com_facebook_tooltip_default = 2130968627;
			
			// aapt resource value: 0x7f040006
			public const int common_android_wear_notification_needs_update_text = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int common_android_wear_update_text = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_title = 2130968593;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_enable_button = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_enable_text = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_title = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_install_button = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_text_phone = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_install_text_tablet = 2130968587;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_title = 2130968585;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_invalid_account_text = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_invalid_account_title = 2130968600;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_needs_enabling_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_network_error_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_network_error_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_notification_needs_update_title = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_notification_ticker = 2130968580;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unknown_issue = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_unsupported_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_unsupported_title = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int common_google_play_services_update_button = 2130968605;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_update_text = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_title = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_updating_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_updating_title = 2130968596;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_button_text = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_button_text_long = 2130968577;
			
			// aapt resource value: 0x7f040037
			public const int fb_app_id = 2130968631;
			
			// aapt resource value: 0x7f040035
			public const int hello = 2130968629;
			
			// aapt resource value: 0x7f040034
			public const int messenger_send_button_text = 2130968628;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MessengerButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MessengerButton_Blue = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MessengerButton_Blue_Large = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int MessengerButton_Blue_Small = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MessengerButton_White = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MessengerButton_White_Large = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MessengerButton_White_Small = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MessengerButtonText = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MessengerButtonText_Blue = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int MessengerButtonText_Blue_Large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MessengerButtonText_Blue_Small = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int MessengerButtonText_White = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int MessengerButtonText_White_Large = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MessengerButtonText_White_Small = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_button = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_button_like = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_button_send = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_button_share = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_loginview_default_style = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_loginview_silver_style = 2131230739;
			
			// aapt resource value: 0x7f080018
			public const int general_theme = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int login_social_button_style = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int main_theme = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int popup_style = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int splash_theme = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int tooltip_bubble_text = 2131230740;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] com_facebook_like_view = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			public static int[] localization = new int[]
			{
					2130771983};
			
			// aapt resource value: 0
			public const int localization_localizationKey = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
